### need 'REST Client' extension installed for running this file
### GET 
GET http://localhost:3001

### returns books in an array by uid
GET http://localhost:3001/MyBooks
Content-Type: application/json

{
    "currUID": "01",
    "title": "D"
}

### Add a new book
POST http://localhost:3001/MyBooks/AddNewBook
Content-Type: application/json

{
    "currUID": "01",
    "title": "D"
}

### Update a book's title by bookID (need to work on)
POST http://localhost:3001/MyBooks/UpdateTitle
Content-Type: application/json

{
    "currUID": "01",
    "bookID": "D",
    "title": "Testing3",
    "newTitle": "New"
}

### Delete a book's title by bookID
POST http://localhost:3001/MyBooks/DeleteBook
Content-Type: application/json

{
    "bookID": "D",
    "title": "l8ywe new title using Update API"
}