version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: books
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
      args:
        NODE_ENV: prod
    image: api
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      <<: *common-variables
    ports:
      - "3001:3001"

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    build:
      dockerfile: Dockerfile
      context: ./client
      args:
        REACT_ENV: prod
    image: client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
