### GET 
GET http://localhost:3001

### returns all books in an array
GET http://localhost:3001/MyBooks
Content-Type: application/json

{
    "currUID": "01",
    "title": "D"
}

### Add a new book
POST http://localhost:3001/MyBooks/AddNewBook
Content-Type: application/json

{
    "currUID": "01",
    "title": "D"
}

### Update a book's title by bookID
POST http://localhost:3001/MyBooks/UpdateTitle
Content-Type: application/json

{
    "bookID": "l8ywe",
    "title": "Testing3",
    "newTitle": "l8ywe new title using Update API"
}

### Delete a book's title by bookID
POST http://localhost:3001/MyBooks/DeleteBook
Content-Type: application/json

{
    "bookID": "l8ywe",
    "title": "l8ywe new title using Update API"
}