name: Development workflow 
on:
  push:
    branches:
      - develop 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - working-directory: ./client
        run: npm install
      - working-directory: ./client
        run: npm test
      - name: Client eslint 
        working-directory: ./client
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
      - name: Server eslint
        working-directory: ./server
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
      - name: Build, Push and Deploy to Heroku 
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  
        with:
          email: anakamura@student.unimelb.edu.au # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          docker_compose_file: 'docker-compose.yaml' # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"api","appname":"it-project-vaaah-dev-api","apptype":"web"},{"imagename":"client","appname":"it-project-vaaah-dev-client","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type